"""Compare Pauli orderings for H, excited H, and H2 Trotter evolution.

This example uses two small Jordan-Wigner Hamiltonians generated by QHAT's
Hamiltonian generator and the repository's local configuration files:

* H/6-31G from ``local_configs/h_atom_631g_jw.py``
* H2/STO-3G from ``local_configs/h2_sto3g_jw.py``

The 6-31G basis gives atomic hydrogen two spatial orbitals.  We diagonalize
its one-electron sector and use the lowest two *distinct* energy levels as H
and excited H (H*).  For H2, we use the ground state in the two-electron
sector.

For each state, the example compares QHAT's requested ordering methods:

* ``None``: preserve the QHAT/OpenFermion input order
* ``lexicographical``: sort the dense Pauli strings
* ``group_evolve_greedy``: color the noncommutation graph and place equal
  colors, hence mutually commuting terms, next to one another

Run from the repository root with:

    python analysis/examples/ordering_error_comparison.py

The default is one first-order Trotter step at t=1 Hartree^-1.  A deliberately
coarse step makes ordering effects visible.  Use ``--help`` for controls.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import sys
from typing import Mapping, Sequence

import networkx as nx
import numpy as np


_REPO_ROOT = next(
    path
    for path in Path(__file__).resolve().parents
    if (path / "analysis" / "ordering.py").exists()
)
for _path in (_REPO_ROOT.parent, _REPO_ROOT):
    if str(_path) not in sys.path:
        sys.path.insert(0, str(_path))

try:
    from qhat.analysis.examples.group_coloring_ordering_demo import (
        H2_STO3G_JW_TERMS,
        build_greedy_coloring_groups,
        group_is_pairwise_commuting,
    )
    from qhat.analysis.matrix_operations import pauli_dict_to_matrix
    from qhat.analysis.ordering import create_commutativity_graph, reorder_paulis
    from qhat.trotter_isomorphism.pauli_keys import dense_string_to_pauli_key
    from qhat.trotter_isomorphism.product_formula import (
        dense_trotter_unitary,
        exact_unitary,
    )
except ModuleNotFoundError:
    from analysis.examples.group_coloring_ordering_demo import (
        H2_STO3G_JW_TERMS,
        build_greedy_coloring_groups,
        group_is_pairwise_commuting,
    )
    from analysis.matrix_operations import pauli_dict_to_matrix
    from analysis.ordering import create_commutativity_graph, reorder_paulis
    from trotter_isomorphism.pauli_keys import dense_string_to_pauli_key
    from trotter_isomorphism.product_formula import (
        dense_trotter_unitary,
        exact_unitary,
    )


ORDERING_METHODS = (None, "lexicographical", "group_evolve_greedy")
ORDERING_LABELS = {
    None: "none",
    "lexicographical": "lexicographical",
    "group_evolve_greedy": "greedy coloring",
}


# Generated with:
#   python -m qhat.hamiltonian_generator.hamgen local_configs/h_atom_631g_jw.py
# The insertion order is the original QHAT/OpenFermion order used by ordering=None.
H_ATOM_631G_JW_TERMS: dict[str, float] = {
    "IIII": +8.13936986647798566e-01,
    "ZIII": -1.74796665629472492e-01,
    "IZII": -1.74796665629472492e-01,
    "IIZI": -6.57789410905925132e-01,
    "IIIZ": -6.57789410905925132e-01,
    "ZZII": +1.57177913387840956e-01,
    "ZIZI": +1.13814507706401155e-01,
    "ZIIZ": +1.52920699899765422e-01,
    "IZZI": +1.52920699899765422e-01,
    "IZIZ": +1.13814507706401155e-01,
    "IIZZ": +1.60586837822822515e-01,
    "ZXZX": -4.65438451711500667e-02,
    "IXZX": +1.00514457922338957e-01,
    "ZYZY": -4.65438451711500667e-02,
    "IYZY": +1.00514457922338957e-01,
    "XIXI": -4.65438451711500736e-02,
    "XZXI": +1.00514457922338957e-01,
    "YIYI": -4.65438451711500736e-02,
    "YZYI": +1.00514457922338957e-01,
    "XXYY": -3.91061921933642739e-02,
    "XYYX": +3.91061921933642739e-02,
    "YXXY": +3.91061921933642739e-02,
    "YYXX": -3.91061921933642739e-02,
    "XZXZ": -5.39706127511888900e-02,
    "YZYZ": -5.39706127511888900e-02,
    "IXIX": -5.39706127511888900e-02,
    "IYIY": -5.39706127511888900e-02,
}

# Reuse the coefficients from the graph-coloring lesson while restoring the
# insertion order emitted by QHAT's H2 local configuration. This makes
# ordering=None a faithful baseline for the generator output.
H2_STO3G_GENERATED_ORDER = (
    "IIII",
    "ZIII",
    "IZII",
    "IIZI",
    "IIIZ",
    "ZZII",
    "ZIZI",
    "ZIIZ",
    "IZZI",
    "IZIZ",
    "IIZZ",
    "XXYY",
    "XYYX",
    "YXXY",
    "YYXX",
)
H2_STO3G_GENERATED_JW_TERMS = {
    pauli: H2_STO3G_JW_TERMS[pauli]
    for pauli in H2_STO3G_GENERATED_ORDER
}


@dataclass(frozen=True)
class EvolutionCase:
    """One physical state and the Hamiltonian used to evolve it."""

    name: str
    basis: str
    particle_number: int
    energy: float
    state: np.ndarray
    terms: Mapping[str, float]

    @property
    def num_qubits(self) -> int:
        return len(next(iter(self.terms)))


@dataclass(frozen=True)
class OrderingResult:
    """Exact numerical diagnostics for one state and one Pauli ordering."""

    case_name: str
    ordering_method: str | None
    energy: float
    operator_error: float
    state_error: float
    infidelity: float
    ordered_paulis: tuple[str, ...]

    @property
    def ordering_label(self) -> str:
        return ORDERING_LABELS[self.ordering_method]


def particle_sector_basis_indices(num_qubits: int, particle_number: int) -> list[int]:
    """Return computational-basis indices with the requested occupation count."""
    if not 0 <= particle_number <= num_qubits:
        raise ValueError(
            f"particle_number must be in 0..{num_qubits}, got {particle_number}."
        )
    return [
        index
        for index in range(2**num_qubits)
        if index.bit_count() == particle_number
    ]


def particle_sector_eigenstate(
    terms: Mapping[str, float],
    particle_number: int,
    distinct_level: int,
    energy_tolerance: float = 1e-9,
) -> tuple[float, np.ndarray]:
    """Return one eigenstate from a distinct energy level in a particle sector.

    Spin degeneracy means the first two one-electron eigenvectors of atomic H
    can have the same energy. ``distinct_level=1`` skips that duplicate energy
    and selects the first genuine orbital excitation.
    """
    if not terms:
        raise ValueError("At least one Pauli term is required.")
    if distinct_level < 0:
        raise ValueError("distinct_level must be nonnegative.")

    num_qubits = len(next(iter(terms)))
    hamiltonian = pauli_dict_to_matrix(terms, num_qubits)
    sector_indices = particle_sector_basis_indices(num_qubits, particle_number)
    sector_hamiltonian = hamiltonian[np.ix_(sector_indices, sector_indices)]
    energies, vectors = np.linalg.eigh(sector_hamiltonian)

    distinct_positions = [0]
    for position in range(1, len(energies)):
        previous = energies[distinct_positions[-1]]
        if abs(energies[position] - previous) > energy_tolerance:
            distinct_positions.append(position)

    if distinct_level >= len(distinct_positions):
        raise ValueError(
            f"Particle sector has only {len(distinct_positions)} distinct energy "
            f"levels; requested level {distinct_level}."
        )

    selected = distinct_positions[distinct_level]
    state = np.zeros(2**num_qubits, dtype=complex)
    state[sector_indices] = vectors[:, selected]
    return float(energies[selected]), state


def build_evolution_cases() -> list[EvolutionCase]:
    """Construct H, H*, and H2 states from fixed-particle-number sectors."""
    h_terms = dict(H_ATOM_631G_JW_TERMS)
    h_ground_energy, h_ground = particle_sector_eigenstate(h_terms, 1, 0)
    h_excited_energy, h_excited = particle_sector_eigenstate(h_terms, 1, 1)

    h2_terms = dict(H2_STO3G_GENERATED_JW_TERMS)
    h2_ground_energy, h2_ground = particle_sector_eigenstate(h2_terms, 2, 0)

    return [
        EvolutionCase(
            name="H ground",
            basis="H/6-31G, one-electron sector",
            particle_number=1,
            energy=h_ground_energy,
            state=h_ground,
            terms=h_terms,
        ),
        EvolutionCase(
            name="H excited",
            basis="H/6-31G, first distinct excited orbital",
            particle_number=1,
            energy=h_excited_energy,
            state=h_excited,
            terms=h_terms,
        ),
        EvolutionCase(
            name="H2 ground",
            basis="H2/STO-3G at 0.7414 Angstrom, two-electron sector",
            particle_number=2,
            energy=h2_ground_energy,
            state=h2_ground,
            terms=h2_terms,
        ),
    ]


def dense_terms_to_sparse(
    terms: Mapping[str, float],
) -> list[tuple[tuple[tuple[int, str], ...], complex]]:
    """Convert QHAT dense Pauli strings to product-formula term tuples."""
    return [
        (dense_string_to_pauli_key(pauli), complex(coefficient))
        for pauli, coefficient in terms.items()
    ]


def noncommutation_graph(terms: Mapping[str, float]) -> nx.Graph:
    """Build QHAT's graph whose edges connect noncommuting Pauli terms."""
    return create_commutativity_graph(
        list(terms.items()),
        pauli_string_format="explicit",
    )


def evaluate_ordering(
    case: EvolutionCase,
    ordering_method: str | None,
    time: float = 1.0,
    num_steps: int = 1,
    method: int = 1,
) -> OrderingResult:
    """Compare one QHAT ordering with exact time evolution."""
    if time < 0:
        raise ValueError("time must be nonnegative.")
    if num_steps <= 0:
        raise ValueError("num_steps must be positive.")

    ordered_terms = reorder_paulis(case.terms, ordering_method)
    sparse_terms = dense_terms_to_sparse(ordered_terms)
    hamiltonian = pauli_dict_to_matrix(case.terms, case.num_qubits)

    exact = exact_unitary(hamiltonian, time)
    trotter = dense_trotter_unitary(
        term_list=sparse_terms,
        time=time,
        num_steps=num_steps,
        n_qubits=case.num_qubits,
        method=method,
    )

    difference = trotter - exact
    exact_state = exact @ case.state
    trotter_state = trotter @ case.state
    overlap = np.vdot(trotter_state, exact_state)
    infidelity = float(np.clip(1.0 - abs(overlap) ** 2, 0.0, 1.0))

    return OrderingResult(
        case_name=case.name,
        ordering_method=ordering_method,
        energy=case.energy,
        operator_error=float(np.linalg.norm(difference, ord=2)),
        state_error=float(np.linalg.norm(trotter_state - exact_state)),
        infidelity=infidelity,
        ordered_paulis=tuple(ordered_terms),
    )


def run_ordering_experiments(
    cases: Sequence[EvolutionCase] | None = None,
    ordering_methods: Sequence[str | None] = ORDERING_METHODS,
    time: float = 1.0,
    num_steps: int = 1,
    method: int = 1,
) -> list[OrderingResult]:
    """Evaluate every requested ordering for every physical case."""
    selected_cases = build_evolution_cases() if cases is None else list(cases)
    return [
        evaluate_ordering(case, ordering, time, num_steps, method)
        for case in selected_cases
        for ordering in ordering_methods
    ]


def print_system_summary(cases: Sequence[EvolutionCase]) -> None:
    """Print state energies and graph-coloring structure for each Hamiltonian."""
    print("Physical Systems")
    print("----------------")
    seen_term_sets: set[tuple[str, ...]] = set()
    for case in cases:
        print(
            f"{case.name:10s}: E = {case.energy:+.12f} Hartree; "
            f"N = {case.particle_number}; {case.basis}"
        )

        signature = tuple(case.terms)
        if signature in seen_term_sets:
            continue
        seen_term_sets.add(signature)

        graph, _, groups = build_greedy_coloring_groups(case.terms)
        assert all(group_is_pairwise_commuting(group) for group in groups)
        print(
            f"             {len(case.terms)} Pauli terms, "
            f"{graph.number_of_edges()} noncommuting pairs, "
            f"{len(groups)} greedy commuting groups"
        )
    print()


def print_results(
    results: Sequence[OrderingResult],
    time: float,
    num_steps: int,
    method: int,
) -> None:
    """Print a compact comparison table."""
    formula = "first" if method == 1 else "second" if method == 2 else str(method)
    print("Trotter Error Comparison")
    print("-------------------------")
    print(f"formula = {formula} order; time = {time}; steps = {num_steps}")
    print()
    print(
        f"{'state':11s} {'ordering':18s} {'operator error':>16s} "
        f"{'state error':>16s} {'infidelity':>16s}"
    )
    for result in results:
        print(
            f"{result.case_name:11s} {result.ordering_label:18s} "
            f"{result.operator_error:16.8e} {result.state_error:16.8e} "
            f"{result.infidelity:16.8e}"
        )


def print_orders(results: Sequence[OrderingResult]) -> None:
    """Print every matrix-product Pauli order used in the comparison."""
    print()
    print("Pauli Orders")
    print("------------")
    seen: set[tuple[tuple[str, ...], str | None]] = set()
    for result in results:
        key = (result.ordered_paulis, result.ordering_method)
        if key in seen:
            continue
        seen.add(key)
        print(f"{result.case_name} / {result.ordering_label}")
        print("  " + " -> ".join(result.ordered_paulis))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--time", type=float, default=1.0)
    parser.add_argument("--steps", type=int, default=1)
    parser.add_argument(
        "--method",
        type=int,
        choices=(1, 2),
        default=1,
        help="QHAT product formula: 1=first order, 2=second order",
    )
    parser.add_argument(
        "--show-orders",
        action="store_true",
        help="Print the dense Pauli sequence produced by every ordering",
    )
    args = parser.parse_args()

    cases = build_evolution_cases()
    results = run_ordering_experiments(
        cases=cases,
        time=args.time,
        num_steps=args.steps,
        method=args.method,
    )

    print("H, Excited H, And H2 Pauli-Ordering Experiment")
    print("================================================")
    print()
    print_system_summary(cases)
    print_results(results, args.time, args.steps, args.method)
    if args.show_orders:
        print_orders(results)


if __name__ == "__main__":
    main()
